import { NestFactory } from '@nestjs/core';
import { NestExpressApplication } from '@nestjs/platform-express';
import { ValidationPipe } from '@nestjs/common';
import { SwaggerModule, DocumentBuilder } from '@nestjs/swagger';
import helmet from 'helmet';
import { AppModule } from './app.module';
import { ShutdownService } from './common/services/shutdown.service';
import { HttpExceptionFilter } from './common/filters/http-exception.filter';
import * as dotenv from 'dotenv';
import * as fs from 'fs';
import * as path from 'path';
import { Request, Response, NextFunction } from 'express';
import * as express from 'express';

// Configuration loading order (later sources do NOT override earlier ones):
//   1. Process env (Docker, shell, systemd) — highest priority
//   2. .env (project-level overrides committed/managed by the user)
//   3. data/.env.generated (Dashboard-managed config; created on first run)
//
// Rationale: explicit env vars from the host/orchestrator must always win
// so that operators can override the Dashboard-saved config without having
// to edit data/.env.generated by hand.
const generatedEnvPath = path.resolve(process.cwd(), 'data', '.env.generated');
const userEnvPath = path.resolve(process.cwd(), '.env');

// Ensure base local data directory exists
const defaultDataDir = path.resolve(process.cwd(), 'data');
if (!fs.existsSync(defaultDataDir)) {
  fs.mkdirSync(defaultDataDir, { recursive: true });
}

// 2. User-managed .env (does not override real process env)
if (fs.existsSync(userEnvPath)) {
  console.log('[Bootstrap] Loading .env from:', userEnvPath);
  dotenv.config({ path: userEnvPath, override: false });
}

// 3. Dashboard-saved config (loads saved infrastructure config)
if (fs.existsSync(generatedEnvPath)) {
  console.log('[Bootstrap] Loading saved configuration from:', generatedEnvPath);
  dotenv.config({ path: generatedEnvPath, override: true });
} else {
  console.log('[Bootstrap] First run detected, creating default configuration...');
  // Create minimal .env.generated with sensible defaults
  const minimalConfig = `# OpenWA Configuration
# Generated automatically on first run
# Edit via Dashboard > Infrastructure or modify this file directly.
# Note: values in process env or project .env take precedence over this file.

# Database (SQLite - no external service required)
DATABASE_TYPE=sqlite
POSTGRES_BUILTIN=false

# Redis & Queue (disabled by default)
REDIS_ENABLED=false
REDIS_BUILTIN=false
QUEUE_ENABLED=false

# Storage (Local filesystem)
STORAGE_TYPE=local
MINIO_BUILTIN=false
STORAGE_PATH=./data/media

# Docker Profiles: none (minimal setup)
`;
  fs.writeFileSync(generatedEnvPath, minimalConfig);
  console.log('[Bootstrap] Created default configuration at:', generatedEnvPath);
  dotenv.config({ path: generatedEnvPath, override: true });
}

interface SavedDatabaseConfig {
  type?: string;
  host?: string;
  port?: string | number;
  username?: string;
  password?: string;
  database?: string;
  sslEnabled?: boolean;
  poolSize?: string | number;
}

interface SavedInfraConfigFile {
  database?: SavedDatabaseConfig;
}

// 4. Load infra-config.json if available
const infraConfigJsonPath = path.resolve(process.cwd(), 'data', 'infra-config.json');
if (fs.existsSync(infraConfigJsonPath)) {
  try {
    const raw = fs.readFileSync(infraConfigJsonPath, 'utf8');
    const saved = JSON.parse(raw) as SavedInfraConfigFile;
    if (saved.database?.type) {
      process.env.DATABASE_TYPE = saved.database.type;
      if (saved.database.type === 'postgres') {
        if (saved.database.host) process.env.DATABASE_HOST = saved.database.host;
        if (saved.database.port) process.env.DATABASE_PORT = String(saved.database.port);
        if (saved.database.username) process.env.DATABASE_USERNAME = saved.database.username;
        if (saved.database.password) process.env.DATABASE_PASSWORD = saved.database.password;
        if (saved.database.database) process.env.DATABASE_NAME = saved.database.database;
        if (saved.database.sslEnabled !== undefined) {
          process.env.DATABASE_SSL = saved.database.sslEnabled ? 'true' : 'false';
        }
        if (saved.database.poolSize) {
          process.env.DATABASE_POOL_SIZE = String(saved.database.poolSize);
        }
      }
    }
  } catch (e) {
    console.warn('[Bootstrap] Could not read infra-config.json:', e);
  }
}

// Ensure configured paths exist or safely fallback to ./data if directory is unwritable
function ensureDirectoryOrFallback(envKey: string, isFile: boolean, defaultRelativePath: string): void {
  const configured = process.env[envKey] || defaultRelativePath;
  const targetDir = isFile ? path.dirname(configured) : configured;
  try {
    if (!fs.existsSync(targetDir)) {
      fs.mkdirSync(targetDir, { recursive: true });
    }
    // Test write permissions
    const testFile = path.join(targetDir, `.write-test-${Date.now()}`);
    fs.writeFileSync(testFile, 'ok');
    fs.unlinkSync(testFile);
  } catch (err) {
    const errorMsg = err instanceof Error ? err.message : String(err);
    console.warn(
      `[Bootstrap] Configured ${envKey}='${configured}' is not writable (${errorMsg}). Falling back to local data directory.`,
    );
    const fallbackPath = isFile
      ? path.join(defaultDataDir, path.basename(configured))
      : path.join(defaultDataDir, path.basename(configured));
    if (!isFile && !fs.existsSync(fallbackPath)) {
      fs.mkdirSync(fallbackPath, { recursive: true });
    }
    process.env[envKey] = fallbackPath;
  }
}

if (process.env.DATABASE_TYPE !== 'postgres') {
  ensureDirectoryOrFallback('DATABASE_NAME', true, './data/openwa.sqlite');
}
ensureDirectoryOrFallback('SESSION_DATA_PATH', false, './data/sessions');
ensureDirectoryOrFallback('STORAGE_LOCAL_PATH', false, './data/media');

async function bootstrap() {
  const app = await NestFactory.create<NestExpressApplication>(AppModule);

  // Increase payload size limit for base64 media and document uploads
  app.use(express.json({ limit: '50mb' }));
  app.use(express.urlencoded({ limit: '50mb', extended: true }));

  // Enable shutdown hooks for graceful shutdown
  app.enableShutdownHooks();

  // Wire up graceful shutdown service
  const shutdownService = app.get(ShutdownService);
  shutdownService.setShutdownCallback(async () => {
    await app.close();
  });

  // Dedicated health check endpoint for Render / Cloud load balancers (returns 200 immediately)
  app.use('/health', (_req: Request, res: Response) => {
    res.status(200).json({ status: 'ok', timestamp: new Date().toISOString() });
  });

  // Serve static files BEFORE global prefix
  const dashboardPath = path.resolve(process.cwd(), process.env.DASHBOARD_PATH || 'dashboard/dist');
  console.log('Dashboard path:', dashboardPath);
  console.log('Dashboard exists:', fs.existsSync(dashboardPath));

  // Serve static files from dashboard with proper caching headers
  app.use(
    '/',
    express.static(dashboardPath, {
      setHeaders: (res: Response, filePath: string) => {
        if (filePath.endsWith('index.html')) {
          res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
          res.setHeader('Pragma', 'no-cache');
          res.setHeader('Expires', '0');
        } else if (filePath.includes('/assets/')) {
          res.setHeader('Cache-Control', 'public, max-age=31536000, immutable');
        }
      },
    }),
  );

  // SPA fallback for React Router (catch ALL non-API routes)
  app.use((req: Request, res: Response, next: NextFunction) => {
    // Let API routes through to NestJS
    if (req.path === '/api' || req.path.startsWith('/api/')) {
      return next();
    }
    // Let WebSocket and event namespaces through to NestJS
    if (req.path.startsWith('/socket.io') || req.path.startsWith('/events')) {
      return next();
    }
    // Let static assets through
    if (req.path.startsWith('/assets/') || req.path.startsWith('/favicon') || req.path.includes('.')) {
      return next();
    }
    // For all other routes, serve React app (index.html)
    const indexPath = path.join(dashboardPath, 'index.html');
    if (fs.existsSync(indexPath)) {
      res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
      res.setHeader('Pragma', 'no-cache');
      res.setHeader('Expires', '0');
      return res.sendFile(indexPath);
    }
    return res
      .status(200)
      .send(
        `<!DOCTYPE html><html><head><title>OpenWA</title></head><body><h2>OpenWA Backend Running</h2><p>Dashboard build not found at ${dashboardPath}. API is available at <a href="/api/docs">/api/docs</a>.</p></body></html>`,
      );
  });

  // Enhanced Security Headers
  app.use(
    helmet({
      contentSecurityPolicy: {
        directives: {
          defaultSrc: ["'self'"],
          styleSrc: ["'self'", "'unsafe-inline'", 'https://fonts.googleapis.com'],
          fontSrc: ["'self'", 'https://fonts.gstatic.com'],
          scriptSrc: ["'self'", "'unsafe-inline'", "'unsafe-eval'"],
          imgSrc: ["'self'", 'data:', 'https:', 'blob:'],
          connectSrc: ["'self'", 'ws:', 'wss:'],
          objectSrc: ["'none'"],
        },
      },
      crossOriginResourcePolicy: { policy: 'cross-origin' },
    }),
  );

  // CORS Configuration
  const allowedOrigins = process.env.CORS_ORIGINS?.split(',').map(o => o.trim()) || ['*'];
  app.enableCors({
    origin: (origin: string | undefined, callback: (err: Error | null, allow?: boolean) => void) => {
      if (!origin) return callback(null, true);
      if (allowedOrigins.includes('*') || allowedOrigins.includes(origin)) {
        callback(null, true);
      } else {
        callback(new Error('Not allowed by CORS'));
      }
    },
    credentials: true,
    methods: ['GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'OPTIONS'],
    allowedHeaders: ['Content-Type', 'X-API-Key', 'Authorization', 'X-Request-ID'],
    exposedHeaders: ['X-RateLimit-Limit', 'X-RateLimit-Remaining', 'X-RateLimit-Reset'],
    maxAge: 86400,
  });

  // Global prefix for API
  app.setGlobalPrefix('api');

  // Global exception filter
  app.useGlobalFilters(new HttpExceptionFilter());

  // Enhanced Validation pipe
  app.useGlobalPipes(
    new ValidationPipe({
      whitelist: true,
      forbidNonWhitelisted: true,
      transform: true,
      transformOptions: {
        enableImplicitConversion: true,
      },
      disableErrorMessages: process.env.NODE_ENV === 'production',
    }),
  );

  // Swagger documentation
  const config = new DocumentBuilder()
    .setTitle('OpenWA API')
    .setDescription('Open Source WhatsApp API Gateway - Free, Self-Hosted HTTP API')
    .setVersion('0.1.6')
    .addApiKey({ type: 'apiKey', name: 'X-API-Key', in: 'header' }, 'X-API-Key')
    .addTag('sessions', 'WhatsApp session management')
    .addTag('messages', 'Send and manage messages')
    .addTag('webhooks', 'Webhook configuration')
    .addTag('contacts', 'Contact management')
    .addTag('groups', 'Group management')
    .addTag('labels', 'Label management')
    .addTag('channels', 'Channel/Newsletter management')
    .addTag('health', 'Health check endpoints')
    .build();

  const document = SwaggerModule.createDocument(app, config);
  SwaggerModule.setup('api/docs', app, document);

  const port = Number(process.env.PORT) || 2785;

  await app.listen(port, '0.0.0.0');

  console.log(`🚀 OpenWA is running on: http://0.0.0.0:${port}`);
  console.log(`🚀 OpenWA is running on: http://localhost:${port}`);
  console.log(`📚 Swagger docs: http://localhost:${port}/api/docs`);
  console.log(`🖥️  Dashboard: http://localhost:${port}/`);
}

void bootstrap();
